env:
    CONFIG: ENCRYPTED[328b268c3c0bad987e083744610d405a8b03144c150244c7d099bc77e18b17de6173d1dfacb54c0ed5ba4ef597b60bd4]
    CIRRUS_SHELL: bash

task:
  name: "CirrusCI-Recovery-Builder"
  timeout_in: 120m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 20G

  Sync_script:
      - git clone $CONFIG &&cd new &&bash bot.sh
